MONDICT = {'REGwrite':0,
           'SRAMwrite':1,
           'start':2,
           'aon':3,
           'don':4,
           'ADdone':5,
           'alldone':6,
           'fifo_adv':7,
           'fifostart':8,
           'DaisyIn[0]':10,
           'DaisyIn[1]':11,
           'DaisyIn[2]':12,
           'DaisyIn[3]':13,
           'DaisyOut[0]':14,
           'DaisyOut[1]':15,
           'DaisyOut[2]':16,
           'DaisyOut[3]':17,
           'd[0]':18,
           'd[1]':19,
           'demod0I[b0]': 26,
           'demod0I[b1]': 27,
           'demod0I[b2]': 28,
           'demod0I[b3]': 29,
           'demod0I[b4]': 30,
           'demod0I[b5]': 31,
           'demod0I[b6]': 32,
           'demod0I[b7]': 33           
           }